### ISSUE TITLE
Breaks action in Ember 1.13

### ISSUE THREAD

**Issue by guatedude2** [IvyApp/ivy-sortable#11]
Actions dont get triggered for some reason with Ember 0.2.7.

**Comment by guatedude2** [comment]
here's more info on the fix:
Looks like Ember 0.2.7 requires a target when calling `triggerAction`

```
    this.triggerAction({
      action: actionName,
      target: this.get('controller'),
      actionContext: contexts
    });
```

added this line but now in the template the controller has to be specified

**Comment by guatedude2** [comment]
Looks like this might be a problem with Ember itself...
https://github.com/emberjs/ember.js/issues/11402

**Comment by rwjblue** [comment]
https://github.com/IvyApp/ivy-sortable/blob/7dd3d825df83998fa4da616edff2fcc9f0d6e22d/addon/views/ivy-sortable.js#L107-L110 needs to be updated to account for the fact that `_parentView` doesn't exist in Ember 1.13+ (should be using `parentView`).

**Comment by guatedude2** [comment]
for some reason using `parentView` returns `null`

**Comment by omghax** [comment]
Yeah, the idea was to make `ivy-sortable` masquerade as a component even though under the hood it's actually a `CollectionView`, so that code was lifted directly from `Ember.Component`. I've changed it to reference `parentView` instead, which seems to work both with Ember 1.13 and older.

**Comment by guatedude2** [comment]
Awesome! Thanks

**Comment by maxscott** [comment]
:+1:

**Comment by guatedude2** [comment]
Hi @omghax I tested out the component with your fix. Seems like the action target object is the content item. 

This is my example where content is a list of items in a model: 

```
// app/templates/card-view.hbs
{{#collection "ivy-sortable" content=content moved="moveCard" revert="200" }}
  {{card details=this}}
{{/collection}}
```

```
// app/controllers/card-view.js
  import Ember from 'ember';

  export default Ember.ArrayController.extend({
    actions: {
      moveCard(card, oldIndex, newIndex) {
        console.log("CARD MOVED", card, oldIndex, newIndex);
      }
    }
  });
```

and the debug of sendAction is Line 80 in ivy_sortable/views/ivy-sortable.js

```
this.triggerAction({
  action: actionName, //this is "moveCard"
  actionContext: contexts //this is an individual card model
});
```

So the controller `moveCard` doesnt work

**Comment by guatedude2** [comment]
moving this to a new issue
